services:
  task-manager-service:
    build:
      context: .
    ports:
      - "8081:8081"
    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://task_db:5432/postgres
      SPRING_DATASOURCE_URL: jdbc:postgresql://task_db:5432/task_manager_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: tata
      SPRING_JPA_HIBERNATE_DDL_AUTO: none

  postgres:
    image: postgres:16
    container_name: task_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tata
      POSTGRES_DB: task_manager_db
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d/

volumes:
  postgres_data:
