spring.application.name=task-manager
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/task_manager_db
spring.datasource.username=postgres
spring.datasource.password=tata
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jakarta.persistence.jdbc.url=jdbc:postgresql://localhost:5432/task_manager_db
